-- MySQL Script generated by MySQL Workbench
-- Sat Jan 13 16:31:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema training_app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `training_app` ;

-- -----------------------------------------------------
-- Schema training_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `training_app` DEFAULT CHARACTER SET utf8 ;
USE `training_app` ;

-- -----------------------------------------------------
-- Table `training_app`.`member_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_app`.`member_rank` ;

CREATE TABLE IF NOT EXISTS `training_app`.`member_rank` (
  `rank_id` VARCHAR(10) NOT NULL DEFAULT '会員ランクID' COMMENT '会員ランク',
  `rank_name` VARCHAR(45) NOT NULL DEFAULT '会員ランク名',
  `create_date` DATETIME NOT NULL,
  `updte_date` DATETIME NOT NULL,
  PRIMARY KEY (`rank_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training_app`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_app`.`user` ;

CREATE TABLE IF NOT EXISTS `training_app`.`user` (
  `user_id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `rank` VARCHAR(10) NOT NULL,
  `age` VARCHAR(10) NOT NULL COMMENT 'ユーザテーブル',
  `state` INT NOT NULL,
  `icon_image` VARCHAR(100) NULL,
  `name` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `updte_date` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_member_rank_idx` (`rank` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training_app`.`training_defualt_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_app`.`training_defualt_menu` ;

CREATE TABLE IF NOT EXISTS `training_app`.`training_defualt_menu` (
  `menu_id` INT NOT NULL,
  `menu_name` VARCHAR(45) NOT NULL,
  `menu_category_id` VARCHAR(45) NOT NULL COMMENT 'デフォルトトレーニングメニューマスタ',
  `description` VARCHAR(45) NULL,
  `create_date` DATETIME NOT NULL,
  `updte_date` DATETIME NOT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training_app`.`menu_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_app`.`menu_category` ;

CREATE TABLE IF NOT EXISTS `training_app`.`menu_category` (
  `category_id` VARCHAR(45) NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `root_category_id` VARCHAR(45) NOT NULL COMMENT 'メニュカテゴリマスタ',
  `create_date` DATETIME NOT NULL,
  `updte_date` DATETIME NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training_app`.`member_defualt_training_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_app`.`member_defualt_training_menu` ;

CREATE TABLE IF NOT EXISTS `training_app`.`member_defualt_training_menu` (
  `traning_menu_id` VARCHAR(45) NOT NULL COMMENT 'menu_id = “defualt_\" + memberid',
  `set` INT NOT NULL,
  `count` INT NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `menu_id` VARCHAR(45) NOT NULL COMMENT 'デフォルトトレーニングメニュー',
  `description` VARCHAR(45) NULL,
  `user_user_id` VARCHAR(45) NOT NULL,
  `training_defualt_menu_menu_id` INT NOT NULL,
  `menu_category_category_id` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `updte_date` DATETIME NOT NULL,
  PRIMARY KEY (`traning_menu_id`, `set`),
  INDEX `fk_member_defualt_training_menu_user1_idx` (`user_user_id` ASC),
  INDEX `fk_member_defualt_training_menu_training_defualt_menu1_idx` (`training_defualt_menu_menu_id` ASC),
  INDEX `fk_member_defualt_training_menu_menu_category1_idx` (`menu_category_category_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training_app`.`training_original_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_app`.`training_original_menu` ;

CREATE TABLE IF NOT EXISTS `training_app`.`training_original_menu` (
  `menu_id` VARCHAR(45) NOT NULL,
  `menu_name` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `menu_category_id` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `create_date` DATETIME NOT NULL,
  `updte_date` DATETIME NOT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training_app`.`member_original_training_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_app`.`member_original_training_menu` ;

CREATE TABLE IF NOT EXISTS `training_app`.`member_original_training_menu` (
  `traning_menu_id` VARCHAR(45) NOT NULL,
  `set` INT NOT NULL,
  `count` INT NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `menu_id` VARCHAR(45) NULL,
  `menu_category_id` VARCHAR(45) NULL,
  `user_user_id` VARCHAR(45) NOT NULL,
  `training_original_menu_menu_id` VARCHAR(45) NOT NULL,
  `menu_category_category_id` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `updte_date` DATETIME NOT NULL,
  PRIMARY KEY (`traning_menu_id`),
  INDEX `fk_member_original_training_menu_user1_idx` (`user_user_id` ASC),
  INDEX `fk_member_original_training_menu_training_original_menu1_idx` (`training_original_menu_menu_id` ASC),
  INDEX `fk_member_original_training_menu_menu_category1_idx` (`menu_category_category_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `training_app`.`training_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `training_app`.`training_history` ;

CREATE TABLE IF NOT EXISTS `training_app`.`training_history` (
  `hisotry_id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `menu_id` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL COMMENT 'トレーニング履歴',
  `create_date` DATETIME NOT NULL,
  `updte_date` DATETIME NOT NULL,
  PRIMARY KEY (`hisotry_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `menu_id_UNIQUE` (`menu_id` ASC),
  UNIQUE INDEX `date_UNIQUE` (`date` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
